// src/components/meals/MealForm.tsx
import React, { useMemo, useRef, useEffect } from 'react';
import { useForm, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Utensils, Info, Hash, Save } from 'lucide-react';
import NutritionButton from '../../ui/NutritionButton';

import type { Meal, MealData, MealPlanItem } from '../../types';
import useProductStore from '../../stores/useProductStore';
import useDishStore from '../../stores/useDishStore';
import useCategoryStore from '../../stores/useCategoryStore';
import useMealTypesStore from '../../stores/useMealTypesStore';
import { useMealStore } from '../../stores/useMealStore';
import Button from '../../ui/Button';
import CollapsibleSection from '../../ui/CollapsibleSection';

import { calculateMealTotals } from '../../utils/nutritionUtils';
import MealBasicInfo from './form/MealBasicInfo';
import MealComposition from './form/MealComposition';

interface MealFormProps {
  meal?: Meal | null;
  onSubmit: (data: MealData) => void;
  onCancel: () => void;
  autoGeneratedName?: string;
  focusName?: boolean;
  openSections?: string[];
  onToggleSection?: (sectionId: string) => void;
}

const MealForm: React.FC<MealFormProps> = ({
  meal,
  onSubmit,
  onCancel,
  autoGeneratedName,
  focusName = false,
  openSections,
  onToggleSection,
}) => {
  const { products } = useProductStore();
  const { dishes } = useDishStore();
  const { categories } = useCategoryStore();
  const { meals: _meals } = useMealStore();
  const { mealTypes } = useMealTypesStore();

  const validationSchema = useMemo(() => {
    return z.object({
      name: z.string().min(1, 'Название обязательно'),
      description: z.string().optional(),
      mealTypeId: z.string().optional(),
      items: z
        .array(
          z.object({
            instanceId: z.string(),
            type: z.enum(['product', 'dish']),
            itemId: z.number(),
            weight: z.number().min(1, 'Вес должен быть больше 0').optional(),
          })
        )
        .min(1, 'Приём пищи должен содержать хотя бы один продукт или блюдо'),
    });
  }, []);

  type MealFormValues = z.infer<typeof validationSchema>;

  // ИЗМЕНЕНО: Реализация открытия в новой вкладке
  const handleEditItem = (item: { type: 'product' | 'dish'; itemId: number }) => {
    let url = '';

    if (item.type === 'product') {
      const product = products.find((p) => p.id === item.itemId);
      if (product) {
        url = `/products?selectedId=${product.id}`;
      }
    } else if (item.type === 'dish') {
      const dish = dishes.find((d) => d.id === item.itemId);
      if (dish) {
        url = `/dishes?selectedId=${dish.id}`;
      }
    }

    if (url) {
      window.open(url, '_blank');
    }
  };

  const {
    control,
    formState: { errors },
    watch,
    setValue,
    handleSubmit,
  } = useForm<MealFormValues>({
    resolver: zodResolver(validationSchema),
    defaultValues: {
      name: meal?.name || '',
      description: meal?.description || '',
      mealTypeId: meal?.mealTypeId ? String(meal.mealTypeId) : '',
      items: meal?.items || [],
    },
  });

  const { fields, append, remove, move, update } = useFieldArray({ control, name: 'items' });
  const watchItems = watch('items');
  const nameInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (!meal && autoGeneratedName) {
      setValue('name', autoGeneratedName);
    }
  }, [meal, autoGeneratedName, setValue]);

  useEffect(() => {
    if (focusName && nameInputRef.current) {
      setTimeout(() => nameInputRef.current?.focus(), 50);
    }
  }, [focusName]);

  const totals = useMemo(() => {
    const itemsToCalculate = watchItems.map((item) => item as MealPlanItem);
    return calculateMealTotals(itemsToCalculate, products, dishes);
  }, [watchItems, products, dishes]);

  const handleAddItem = (itemId: number, type: 'product' | 'dish') => {
    let defaultWeight = 100;
    if (type === 'product') {
      const product = products.find((p) => p.id === itemId);
      defaultWeight =
        product && product.portions.length > 0 ? Number(product.portions[0].weight) : 100;
    } else if (type === 'dish') {
      const dish = dishes.find((d) => d.id === itemId);
      if (dish) {
        defaultWeight = Number(dish.products.reduce((sum, p) => sum + Number(p.weight), 0) || 100);
      }
    }
    append({
      instanceId: `${type}-${Date.now()}`,
      type,
      itemId,
      weight: Number(defaultWeight),
    });
  };

  const handleUpdateWeight = (index: number, weight: number) => {
    if (watchItems[index]) {
      update(index, { ...watchItems[index], weight: Number(weight) });
    }
  };

  const processSubmit = (data: MealFormValues) => {
    const mealTypeIdNumber =
      data.mealTypeId && data.mealTypeId !== '' ? Number(data.mealTypeId) : undefined;
    const mealData: MealData = {
      name: data.name?.trim() || 'Без названия',
      description: data.description,
      mealTypeId: mealTypeIdNumber,
      items: data.items.map(({ instanceId: _, ...item }) => item) as MealPlanItem[],
    };
    onSubmit(mealData);
  };

  const currentOpenSections = openSections ?? ['basic-info', 'composition'];
  const handleToggleSection =
    onToggleSection ??
    (() => {
      /* noop */
    });

  return (
    <div className="space-y-6">
      {/* SECTION 1: BASIC INFO */}
      <CollapsibleSection
        id="basic-info"
        title="Основная информация"
        icon={<Info className="w-4 h-4 text-primary" />}
        isOpen={currentOpenSections.includes('basic-info')}
        onToggle={handleToggleSection}
        showBorder={false}
        actionButton={
          <div className="flex items-center gap-2 min-w-[280px] justify-end">
            <Button
              type="button"
              variant="ghost"
              onClick={(e) => {
                e.stopPropagation();
                onCancel();
              }}
            >
              Отмена
            </Button>
            <Button
              type="button"
              variant="primary"
              onClick={(e) => {
                e.stopPropagation();
                handleSubmit(processSubmit)();
              }}
              icon={Save}
              size="icon"
            />
          </div>
        }
        gradientFrom="gradient-basic-info"
      >
        <MealBasicInfo
          control={control}
          errors={errors}
          mealTypes={mealTypes}
          isNew={!meal}
          nameRef={nameInputRef}
        />
      </CollapsibleSection>

      {/* SECTION 2: COMPOSITION */}
      <CollapsibleSection
        id="composition"
        title="Состав"
        icon={<Utensils className="w-4 h-4 text-primary" />}
        isOpen={currentOpenSections.includes('composition')}
        onToggle={handleToggleSection}
        showBorder={false}
        summaryContent={
          <span className="flex items-center gap-1.5 text-sm text-muted-foreground">
            <Hash className="w-3.5 h-3.5" />
            {watchItems.length}
          </span>
        }
        headerContent={
          <NutritionButton
            calories={totals.calories}
            proteins={totals.proteins}
            fats={totals.fats}
            carbs={totals.carbs}
            weight={totals.weight}
          />
        }
        gradientFrom="gradient-meal"
      >
        <MealComposition
          fields={fields}
          items={watchItems as MealPlanItem[]}
          products={products}
          dishes={dishes}
          categories={categories}
          onAdd={handleAddItem}
          onRemove={remove}
          onUpdateWeight={handleUpdateWeight}
          onMove={move}
          onEditItem={handleEditItem}
          error={errors.items?.message as string}
        />
      </CollapsibleSection>
    </div>
  );
};

export default MealForm;
