// src/pages/MealsPage.tsx

import React, { useState, useMemo, useCallback, useEffect, useRef } from 'react';
// ... (imports remain the same)
import { flushSync } from 'react-dom';
import {
  CirclePlus,
  Utensils,
  Trash2,
  Copy,
  Upload,
  X,
  CheckSquare,
  CheckCheck,
  LayoutList,
  Grid3X3,
  Filter,
  Download,
} from 'lucide-react';
import { useSearchParams } from 'react-router-dom';

import { useMealStore } from '../stores/useMealStore';
import useProductStore from '../stores/useProductStore';
import useDishStore from '../stores/useDishStore';
import useMealTypesStore from '../stores/useMealTypesStore';
import { useSettingsStore } from '../stores/useSettingsStore';
import { useViewMode } from '../hooks/useViewMode';
import type { Meal, MealData } from '../types';
import Button from '../ui/Button';
import ConfirmModal from '../ui/ConfirmModal';
import MealDetail from '../components/meals/MealDetail';
import { generateUniqueMealName } from '../components/meals/mealFormUtils';
import { exportBulkMealsToJson, importDataFromJson } from '../utils/backup';

import MealListEntry from '../components/meals/MealListEntry';

const MealsPage: React.FC = () => {
  // ... (state logic remains the same, omitted for brevity)
  const { meals, addMeal, removeMeal } = useMealStore();
  const { products } = useProductStore();
  const { dishes } = useDishStore();
  const { mealTypes } = useMealTypesStore();
  const { viewMode, toggleViewMode } = useViewMode('meals');
  const getVisibleFields = useSettingsStore((state) => state.getVisibleFields);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [activeId, setActiveId] = useState<number | null>(null);
  const [detailEditTrigger, setDetailEditTrigger] = useState(0);
  const [creatingMeal, setCreatingMeal] = useState(false);
  const [isDetailEditing, setIsDetailEditing] = useState(false);
  const [mealToDelete, setMealToDelete] = useState<Meal | null>(null);
  const [openSections, setOpenSections] = useState<string[]>(['basic-info', 'composition']);
  const [showBulkDeleteConfirm, setShowBulkDeleteConfirm] = useState(false);
  const [searchParams, setSearchParams] = useSearchParams();
  const [selectedMealIds, setSelectedMealIds] = useState<number[]>([]);
  const [showMultiSelect, setShowMultiSelect] = useState(false);
  const [_autoGeneratedName, setAutoGeneratedName] = useState<string>('');
  const visibleFields = useMemo(() => getVisibleFields('meals'), [getVisibleFields]);

  // ... (effects and handlers remain the same)
  useEffect(() => {
    const selectedId = searchParams.get('selectedId');
    const mealId = searchParams.get('mealId');
    const targetId = mealId || selectedId;
    if (targetId && meals.some((m) => m.id === Number(targetId))) {
      flushSync(() => {
        setActiveId(Number(targetId));
      });
      setSearchParams({}, { replace: true });
      setTimeout(() => {
        document.getElementById('meal-detail-pane')?.scrollIntoView({ behavior: 'smooth' });
      }, 100);
    }
  }, [searchParams, meals, setSearchParams]);

  const handleToggleSection = useCallback((sectionId: string) => {
    setOpenSections((prev) =>
      prev.includes(sectionId) ? prev.filter((id) => id !== sectionId) : [...prev, sectionId]
    );
  }, []);

  const selectedMeal = useMemo(
    () => meals.find((m) => m.id === activeId) || null,
    [activeId, meals]
  );
  const handleEdit = useCallback((mealId: number) => {
    setActiveId(mealId);
    setIsDetailEditing(true);
    setDetailEditTrigger((t) => t + 1);
  }, []);
  const generateMealName = useCallback(() => generateUniqueMealName(meals), [meals]);
  useEffect(() => {
    if (creatingMeal || _autoGeneratedName) setAutoGeneratedName(generateMealName());
  }, [creatingMeal, _autoGeneratedName, generateMealName]);

  const handleInlineCreate = useCallback(
    async (formData: MealData) => {
      const dataWithName = { ...formData, name: formData.name.trim() || generateMealName() };
      const created = addMeal(dataWithName);
      setActiveId(created.id);
      setCreatingMeal(false);
    },
    [addMeal, generateMealName]
  );

  const handleRequestDelete = useCallback((meal: Meal) => setMealToDelete(meal), []);
  const handleConfirmDelete = useCallback(() => {
    if (!mealToDelete) return;
    if (mealToDelete.id === activeId) setActiveId(null);
    removeMeal(mealToDelete.id);
    setMealToDelete(null);
  }, [mealToDelete, activeId, removeMeal]);
  const toggleMultiSelect = () => {
    setShowMultiSelect((s) => !s);
    if (showMultiSelect) setSelectedMealIds([]);
  };
  const toggleMealSelection = useCallback((mealId: number) => {
    setSelectedMealIds((prev) =>
      prev.includes(mealId) ? prev.filter((id) => id !== mealId) : [...prev, mealId]
    );
  }, []);
  const selectAllMeals = () => setSelectedMealIds(meals.map((meal) => meal.id));
  const exitMultiSelectMode = () => {
    setShowMultiSelect(false);
    setSelectedMealIds([]);
  };
  const handleBulkDelete = () => {
    if (selectedMealIds.length === 0) return;
    setShowBulkDeleteConfirm(true);
  };
  const handleConfirmBulkDelete = () => {
    selectedMealIds.forEach((id) => {
      if (id === activeId) setActiveId(null);
      removeMeal(id);
    });
    exitMultiSelectMode();
    setShowBulkDeleteConfirm(false);
  };
  const handleBulkClone = () => {
    if (selectedMealIds.length === 0) return;
    console.log(`Cloning meals: ${selectedMealIds.join(', ')}`);
  };
  const handleBulkExport = () => {
    if (selectedMealIds.length === 0) return;
    const selectedMeals = meals.filter((meal) => selectedMealIds.includes(meal.id));
    exportBulkMealsToJson(selectedMeals);
  };
  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      importDataFromJson(file);
    }
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <input
        type="file"
        ref={fileInputRef}
        onChange={handleFileChange}
        accept=".json"
        className="hidden"
        aria-hidden="true"
        tabIndex={-1}
      />
      <div className="mb-6 sm:mb-8 px-4 sm:px-2">
        <div className="flex items-center justify-between gap-4">
          <h1 className="text-2xl sm:text-3xl font-semibold text-foreground tracking-tight">
            Приёмы пищи
          </h1>
          <div className="flex items-center gap-2 min-w-[320px] justify-end">
            {/* ... Buttons ... (omitted for brevity) ... */}
            {!showMultiSelect ? (
              <>
                <Button variant="secondary" size="icon" title="Фильтры">
                  <Filter className="w-4 h-4" />
                </Button>
                <Button
                  variant="secondary"
                  size="icon"
                  onClick={() => fileInputRef.current?.click()}
                  title="Импорт"
                >
                  <Download className="w-4 h-4" />
                </Button>
                <Button onClick={toggleViewMode} variant="secondary" size="icon" title="Вид">
                  {viewMode === 'default' ? (
                    <LayoutList className="w-4 h-4" />
                  ) : (
                    <Grid3X3 className="w-4 h-4" />
                  )}
                </Button>
                <Button
                  onClick={toggleMultiSelect}
                  variant="secondary"
                  size="icon"
                  title="Выделить"
                >
                  <CheckSquare className="w-4 h-4" />
                </Button>
                <Button
                  onClick={() => {
                    if (isDetailEditing) return;
                    setCreatingMeal(true);
                    setActiveId(null);
                    setOpenSections(['basic-info', 'composition']);
                  }}
                  disabled={isDetailEditing || creatingMeal}
                  variant="primary"
                  size="icon"
                  className={creatingMeal ? 'bg-primary/80' : ''}
                >
                  <CirclePlus className="w-4 h-4" />
                </Button>
              </>
            ) : (
              <div className="flex items-center gap-2 h-9 min-w-[320px] justify-end">
                <div className="bg-primary/10 text-primary px-3 py-2 rounded-lg text-sm font-medium flex items-center">
                  <span>{`${selectedMealIds.length} из ${meals.length} выделено`}</span>
                </div>
                <Button
                  variant="secondary"
                  size="icon"
                  onClick={selectAllMeals}
                  disabled={selectedMealIds.length === meals.length}
                >
                  <CheckCheck className="w-4 h-4" />
                </Button>
                <div className="flex items-center gap-1">
                  <Button
                    variant="secondary"
                    size="icon"
                    onClick={handleBulkClone}
                    disabled={selectedMealIds.length === 0}
                  >
                    <Copy className="w-4 h-4" />
                  </Button>
                  <Button
                    variant="secondary"
                    size="icon"
                    onClick={handleBulkExport}
                    disabled={selectedMealIds.length === 0}
                  >
                    <Upload className="w-4 h-4" />
                  </Button>
                  <Button
                    variant="danger"
                    size="icon"
                    onClick={handleBulkDelete}
                    disabled={selectedMealIds.length === 0}
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
                <Button onClick={exitMultiSelectMode} variant="ghost" size="icon">
                  <X className="w-4 h-4" />
                </Button>
              </div>
            )}
          </div>
        </div>
      </div>

      {meals.length > 0 || creatingMeal ? (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 lg:gap-6">
          <div className="lg:col-span-1 space-y-3 overflow-y-auto pr-2 custom-scrollbar max-h-[calc(100vh-12rem)] pl-1 pb-4 pt-2">
            {meals.map((meal) => (
              <MealListEntry
                key={meal.id}
                meal={meal}
                viewMode={viewMode}
                isActive={activeId === meal.id}
                isMultiSelected={selectedMealIds.includes(meal.id)}
                isSelectionDisabled={isDetailEditing && activeId !== null && meal.id !== activeId}
                showMultiSelect={showMultiSelect}
                visibleFields={visibleFields}
                products={products}
                dishes={dishes}
                mealTypes={mealTypes}
                onSelect={() => setActiveId(activeId === meal.id ? null : meal.id)}
                onToggleMultiSelect={() => {
                  setShowMultiSelect(true);
                  setSelectedMealIds([meal.id]);
                }}
                onMultiSelect={() => toggleMealSelection(meal.id)}
                onEdit={() => handleEdit(meal.id)}
                onDelete={() => handleRequestDelete(meal)}
              />
            ))}
          </div>

          {/* ИСПРАВЛЕНО: Убран pr-6 отсюда. */}
          <div
            className="lg:col-span-2 hidden lg:block max-h-[calc(100vh-12rem)] overflow-y-auto custom-scrollbar pt-2 pb-20"
            id="meal-detail-pane"
          >
            {/* ИСПРАВЛЕНО: Добавлен внутренний контейнер с отступами pr-6 pl-1 */}
            <div className="pl-1 pr-6">
              {creatingMeal ? (
                <MealDetail
                  meal={null}
                  isCreating={true}
                  onEdit={() => {
                    /* noop */
                  }}
                  openSections={openSections}
                  onToggleSection={handleToggleSection}
                  onStartEdit={() => setIsDetailEditing(true)}
                  onFinishEdit={() => setIsDetailEditing(false)}
                  onSaveNew={handleInlineCreate}
                  onCancelCreation={() => setCreatingMeal(false)}
                />
              ) : selectedMeal ? (
                <MealDetail
                  meal={selectedMeal}
                  onEdit={() => setIsDetailEditing(true)}
                  editTrigger={detailEditTrigger}
                  openSections={openSections}
                  onToggleSection={(id) =>
                    setOpenSections((prev) =>
                      prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]
                    )
                  }
                  onStartEdit={() => setIsDetailEditing(true)}
                  onFinishEdit={() => setIsDetailEditing(false)}
                />
              ) : (
                <div className="h-full flex items-start justify-center pt-16">
                  <div className="text-center p-4">
                    <div className="w-20 h-20 bg-muted rounded-2xl flex items-center justify-center mx-auto mb-4">
                      <Utensils className="w-10 h-10 text-muted-foreground" />
                    </div>
                    <h3 className="text-lg font-medium text-foreground mb-2">
                      Выберите приём пищи
                    </h3>
                    <p className="text-muted-foreground">
                      Кликните на карточку для просмотра подробной информации.
                    </p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      ) : (
        <div className="h-full flex flex-col items-center justify-center py-16">
          <Utensils className="w-12 h-12 mx-auto mb-4 opacity-50" />
          <h3 className="text-lg font-medium text-foreground">Приёмов пищи пока нет</h3>
          <p className="text-sm text-muted-foreground mt-2">
            Создайте первый шаблон, чтобы быстро добавлять его в раскладки.
          </p>
          <Button
            onClick={() => {
              setCreatingMeal(true);
              setActiveId(null);
              setOpenSections(['basic-info', 'composition']);
            }}
            className="mt-4"
          >
            <CirclePlus className="w-4 h-4 mr-2" />
            Создать первый приём пищи
          </Button>
        </div>
      )}

      {/* ... Modals (omitted) ... */}
      <ConfirmModal
        isOpen={!!mealToDelete}
        onClose={() => setMealToDelete(null)}
        onConfirm={handleConfirmDelete}
        title="Подтверждение"
        variant="danger"
        confirmText="Удалить"
      >
        <p>
          Удалить приём пищи <span className="font-bold">{mealToDelete?.name}</span>?
        </p>
      </ConfirmModal>
      <ConfirmModal
        isOpen={showBulkDeleteConfirm}
        onClose={() => setShowBulkDeleteConfirm(false)}
        onConfirm={handleConfirmBulkDelete}
        title="Подтверждение"
        variant="danger"
        confirmText="Удалить"
      >
        <p>Вы уверены, что хотите удалить {selectedMealIds.length} приёмов пищи?</p>
      </ConfirmModal>
    </div>
  );
};

export default MealsPage;
