import React, { useMemo, useState, useCallback, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Utensils,
  Trash2,
  Copy,
  Share,
  X,
  CheckSquare,
  CheckCheck,
  LayoutList,
  Grid3X3,
  Filter,
  UploadCloud,
} from 'lucide-react';
import { useMealStore } from '../stores/useMealStore';
import useProductStore from '../stores/useProductStore';
import useDishStore from '../stores/useDishStore';
import { useIsMobile } from '../hooks/useIsMobile';
import { useViewMode } from '../hooks/useViewMode';
import type { Meal, MealData } from '../types';
import Button from '../ui/Button';
import EntityCard from '../ui/EntityCard';
import EntityListItem from '../ui/EntityListItem'; // <<-- 1. Импортируем новый компонент
import { mealEntityConfig } from '../config/mealEntityConfig';
import { calculateNutrition } from '../components/meals/mealFormUtils';
import Modal from '../ui/Modal';
import ConfirmModal from '../ui/ConfirmModal';
import MealForm from '../components/meals/MealForm';
import MealDetail from '../components/meals/MealDetail';
import CreateMealButton from '../components/meals/CreateMealButton';
import { generateUniqueMealName } from '../components/meals/mealFormUtils';

const MealsPage: React.FC = () => {
  const { meals, addMeal, updateMeal, removeMeal, getNextMealId } = useMealStore();
  const { products } = useProductStore();
  const { dishes } = useDishStore();
  const isMobile = useIsMobile();
  const navigate = useNavigate();
  const { viewMode, toggleViewMode } = useViewMode('meals', 'default');
  const [activeId, setActiveId] = useState<number | null>(null);
  const [detailEditTrigger, setDetailEditTrigger] = useState(0);
  const [showFormModal, setShowFormModal] = useState(false);
  const [editingMeal, setEditingMeal] = useState<Meal | null>(null);
  const [creatingMeal, setCreatingMeal] = useState(false);
  const [isDetailEditing, setIsDetailEditing] = useState(false);
  const [mealToDelete, setMealToDelete] = useState<Meal | null>(null);
  const [openSections, setOpenSections] = useState<string[]>(['basic-info', 'composition']);
  const [showBulkDeleteConfirm, setShowBulkDeleteConfirm] = useState(false);

  const [selectedMealIds, setSelectedMealIds] = useState<number[]>([]);
  const [showMultiSelect, setShowMultiSelect] = useState(false);
  const [autoGeneratedName, setAutoGeneratedName] = useState<string>('');
  const [editSubmitTrigger, setEditSubmitTrigger] = useState(0);
  const [editCancelTrigger, setEditCancelTrigger] = useState(0);

  const selectedMeal = useMemo(
    () => meals.find((m) => m.id === activeId) || null,
    [activeId, meals]
  );

  const handleEdit = useCallback((meal: Meal) => {
    setActiveId(meal.id);
    setIsDetailEditing(true);
    setOpenSections((prev) => (prev.includes('basic-info') ? prev : [...prev, 'basic-info']));
    setDetailEditTrigger((t) => t + 1);
  }, []);

  const generateMealName = useCallback(() => {
    return generateUniqueMealName(meals, getNextMealId());
  }, [meals, getNextMealId]);

  useEffect(() => {
    if (creatingMeal || showFormModal) {
      setAutoGeneratedName(generateMealName());
    }
  }, [creatingMeal, showFormModal, generateMealName]);

  const handleInlineCreate = useCallback(
    (formData: MealData) => {
      const dataWithName = {
        ...formData,
        name: formData.name.trim() || generateMealName(),
      };
      const created = addMeal(dataWithName);
      setActiveId(created.id);
      setCreatingMeal(false);
    },
    [addMeal, generateMealName]
  );

  const handleFormSubmit = useCallback(
    (formData: MealData) => {
      if (editingMeal) {
        updateMeal(editingMeal.id, formData);
      } else {
        const dataWithName = {
          ...formData,
          name: formData.name.trim() || generateMealName(),
        };
        const created = addMeal(dataWithName);
        setActiveId(created.id);
      }
      setShowFormModal(false);
      setEditingMeal(null);
    },
    [editingMeal, addMeal, updateMeal, generateMealName]
  );

  const handleRequestDelete = useCallback((meal: Meal) => setMealToDelete(meal), []);
  const handleConfirmDelete = useCallback(() => {
    if (!mealToDelete) return;
    if (mealToDelete.id === activeId) setActiveId(null);
    removeMeal(mealToDelete.id);
    setMealToDelete(null);
  }, [mealToDelete, activeId, removeMeal]);

  const toggleMultiSelect = () => {
    setShowMultiSelect((s) => !s);
    if (showMultiSelect) setSelectedMealIds([]);
  };

  const toggleMealSelection = (mealId: number) => {
    setSelectedMealIds((prev: number[]) =>
      prev.includes(mealId) ? prev.filter((id) => id !== mealId) : [...prev, mealId]
    );
  };

  const selectAllMeals = () => setSelectedMealIds(meals.map((meal: Meal) => meal.id));
  const exitMultiSelectMode = () => {
    setShowMultiSelect(false);
    setSelectedMealIds([]);
  };

  const handleBulkDelete = () => {
    if (selectedMealIds.length === 0) return;
    setShowBulkDeleteConfirm(true);
  };

  const handleConfirmBulkDelete = () => {
    selectedMealIds.forEach((id) => {
      if (id === activeId) setActiveId(null);
      removeMeal(id);
    });
    exitMultiSelectMode();
    setShowBulkDeleteConfirm(false);
  };

  const handleBulkClone = () => {
    if (selectedMealIds.length === 0) return;
    console.log(`Cloning meals: ${selectedMealIds.join(', ')}`);
  };

  const handleBulkExport = () => {
    if (selectedMealIds.length === 0) return;
    console.log(`Exporting meals: ${selectedMealIds.join(', ')}`);
  };

  // details are no longer shown on cards; counts are included in nutrition block

  return (
    <div className="max-w-7xl mx-auto">
      <div className="mb-6 sm:mb-8 px-4 sm:px-2">
        <div className="flex items-center justify-between gap-4">
          <h1 className="text-2xl sm:text-3xl font-semibold text-foreground tracking-tight">
            Приёмы пищи
          </h1>
          <div className="flex items-center gap-2 min-w-[320px] justify-end">
            {!showMultiSelect ? (
              <>
                <Button
                  onClick={() => console.log('Filters would be implemented here')}
                  variant="secondary"
                  size="icon"
                  title="Фильтры"
                  aria-label="Показать фильтры"
                >
                  <Filter className="w-4 h-4" />
                </Button>

                <Button variant="secondary" size="icon" title="Импорт" aria-label="Импорт">
                  <UploadCloud className="w-4 h-4" />
                </Button>

                <Button
                  onClick={toggleViewMode}
                  variant="secondary"
                  size="icon"
                  title={viewMode === 'default' ? 'Компактный вид' : 'Полный вид'}
                  aria-label={viewMode === 'default' ? 'Компактный вид' : 'Полный вид'}
                >
                  {viewMode === 'default' ? (
                    <LayoutList className="w-4 h-4" />
                  ) : (
                    <Grid3X3 className="w-4 h-4" />
                  )}
                </Button>

                <Button
                  onClick={toggleMultiSelect}
                  variant="secondary"
                  size="icon"
                  title="Выделить"
                  aria-label="Выделить"
                >
                  <CheckSquare className="w-4 h-4" />
                </Button>

                <CreateMealButton
                  onClick={() => {
                    if (isDetailEditing) return;
                    setCreatingMeal(true);
                    setActiveId(null);
                    setOpenSections(['basic-info', 'composition']);
                  }}
                  disabled={isDetailEditing || creatingMeal}
                />
              </>
            ) : (
              <div className="flex items-center gap-2 h-9 min-w-[320px] justify-end">
                <div className="bg-primary/10 text-primary px-3 py-2 rounded-lg text-sm font-medium flex items-center gap-2">
                  <span>{selectedMealIds.length}</span>
                  <span className="text-primary/70">из {meals.length} выделено</span>
                </div>

                <Button
                  variant="secondary"
                  size="icon"
                  onClick={selectAllMeals}
                  disabled={selectedMealIds.length === meals.length}
                  title="Выделить все"
                >
                  <CheckCheck className="w-4 h-4" />
                </Button>

                <div className="flex items-center gap-1">
                  <Button
                    variant="secondary"
                    size="icon"
                    onClick={handleBulkClone}
                    disabled={selectedMealIds.length === 0}
                    title="Клонировать"
                  >
                    <Copy className="w-4 h-4" />
                  </Button>
                  <Button
                    variant="secondary"
                    size="icon"
                    onClick={handleBulkExport}
                    disabled={selectedMealIds.length === 0}
                    title="Экспорт"
                  >
                    <Share className="w-4 h-4" />
                  </Button>
                  <Button
                    variant="danger"
                    size="icon"
                    onClick={handleBulkDelete}
                    disabled={selectedMealIds.length === 0}
                    title="Удалить"
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>

                <Button onClick={exitMultiSelectMode} variant="ghost" size="icon" title="Закрыть">
                  <X className="w-4 h-4" />
                </Button>
              </div>
            )}
          </div>
        </div>
      </div>

      {meals.length > 0 || creatingMeal ? (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 lg:gap-6">
          <div className="lg:col-span-1 space-y-3 overflow-y-auto pr-2 custom-scrollbar max-h-[calc(100vh-12rem)]">
            {meals.map((meal) => {
              // Compute totals for nutrition and weight
              let totalCalories = 0,
                totalProteins = 0,
                totalFats = 0,
                totalCarbs = 0,
                totalWeight = 0;

              meal.items.forEach((item) => {
                const n = calculateNutrition(item as any, products, dishes);
                if (n) {
                  totalCalories += n.calories;
                  totalProteins += n.proteins;
                  totalFats += n.fats;
                  totalCarbs += n.carbs;
                }
                if (item.type === 'product') {
                  totalWeight += (item as any).weight || 0;
                } else if (item.type === 'dish') {
                  const dish = dishes.find((d) => d.id === item.itemId);
                  if (dish) {
                    totalWeight += dish.products.reduce((sum, p) => sum + p.weight, 0);
                  }
                }
              });
              const actions = mealEntityConfig
                .getActions({
                  onEdit: () => handleEdit(meal),
                  onDelete: () => handleRequestDelete(meal),
                })
                .map((action) => ({
                  ...action,
                  disabled: isDetailEditing && meal.id !== activeId,
                  onClick: (e: React.MouseEvent) => {
                    e.preventDefault();
                    e.stopPropagation();
                    if (isDetailEditing && meal.id !== activeId) return;
                    if (action.label === 'Редактировать') {
                      handleEdit(meal);
                    } else if (action.label === 'Удалить') {
                      handleRequestDelete(meal);
                    }
                  },
                }));

              const isCardDisabled = isDetailEditing && meal.id !== activeId;

              // <<-- 2. Условный рендеринг здесь
              return viewMode === 'compact' ? (
                <EntityListItem
                  key={meal.id}
                  title={mealEntityConfig.views.card.title(meal)}
                  icon={mealEntityConfig.getIcon(meal)}
                  borderColor={mealEntityConfig.getBorderColor(meal)}
                  isSelected={activeId === meal.id}
                  isMultiSelected={selectedMealIds.includes(meal.id)}
                  onSelect={isCardDisabled ? undefined : () => setActiveId(meal.id)}
                  onMultiSelect={isCardDisabled ? undefined : () => toggleMealSelection(meal.id)}
                  menuItems={actions}
                  showMultiSelect={showMultiSelect}
                  variant="meal"
                  nutrition={{
                    calories: Math.round(totalCalories),
                    weight: Math.round(totalWeight),
                    itemsCount: meal.items.length,
                  }}
                />
              ) : (
                <EntityCard
                  key={meal.id}
                  title={mealEntityConfig.views.card.title(meal)}
                  icon={mealEntityConfig.getIcon(meal)}
                  borderColor={mealEntityConfig.getBorderColor(meal)}
                  isSelected={activeId === meal.id}
                  isMultiSelected={selectedMealIds.includes(meal.id)}
                  onSelect={isCardDisabled ? undefined : () => setActiveId(meal.id)}
                  onMultiSelect={isCardDisabled ? undefined : () => toggleMealSelection(meal.id)}
                  menuItems={actions}
                  showMultiSelect={showMultiSelect}
                  variant="meal"
                  nutrition={{
                    calories: Math.round(totalCalories),
                    proteins: Math.round(totalProteins * 10) / 10,
                    fats: Math.round(totalFats * 10) / 10,
                    carbs: Math.round(totalCarbs * 10) / 10,
                    weight: Math.round(totalWeight),
                    itemsCount: meal.items.length,
                  }}
                  // viewMode prop is removed
                />
              );
            })}
          </div>

          <div className="lg:col-span-2 hidden lg:block max-h-[calc(100vh-12rem)] overflow-y-auto pr-2 custom-scrollbar">
            {creatingMeal ? (
              <div className="pl-1">
                <MealForm
                  meal={null}
                  onSubmit={handleInlineCreate}
                  onCancel={() => setCreatingMeal(false)}
                  autoGeneratedName={autoGeneratedName}
                  focusName
                />
              </div>
            ) : selectedMeal ? (
              <MealDetail
                meal={selectedMeal}
                onEdit={() => selectedMeal && navigate(`/meals/${selectedMeal.id}/edit`)}
                editTrigger={detailEditTrigger}
                openSections={openSections}
                onToggleSection={(id) =>
                  setOpenSections((prev) =>
                    prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]
                  )
                }
                onStartEdit={() => setIsDetailEditing(true)}
                onFinishEdit={() => setIsDetailEditing(false)}
                editSubmitTrigger={editSubmitTrigger}
                editCancelTrigger={editCancelTrigger}
              />
            ) : (
              <div className="h-full flex items-start justify-center pt-16">
                <div className="text-center p-4">
                  <div className="w-20 h-20 bg-muted rounded-2xl flex items-center justify-center mx-auto mb-4">
                    <Utensils className="w-10 h-10 text-muted-foreground" />
                  </div>
                  <h3 className="text-lg font-medium text-foreground mb-2">Выберите приём пищи</h3>
                  <p className="text-muted-foreground">
                    Кликните на карточку для просмотра подробной информации.
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      ) : (
        <div className="h-full flex flex-col items-center justify-center py-16">
          <Utensils className="w-12 h-12 mx-auto mb-4 opacity-50" />
          <h3 className="text-lg font-medium text-foreground">Приёмов пищи пока нет</h3>
          <p className="text-sm text-muted-foreground mt-2">
            Создайте первый шаблон, чтобы быстро добавлять его в раскладки.
          </p>
          <div className="mt-4 inline-block">
            <CreateMealButton
              onClick={() => {
                setCreatingMeal(true);
                setActiveId(null);
                setOpenSections(['basic-info', 'composition']);
              }}
              variant="primary"
              showText={true}
            />
          </div>
        </div>
      )}

      {isMobile && activeId !== null && (
        <div className="lg:hidden">
          <Modal
            isOpen={activeId !== null}
            onClose={() => setActiveId(null)}
            title={selectedMeal?.name || 'Детали'}
          >
            <MealDetail
              meal={selectedMeal}
              onEdit={() => {
                if (selectedMeal) {
                  handleEdit(selectedMeal);
                  setActiveId(null);
                }
              }}
              openSections={openSections}
              onToggleSection={(id) =>
                setOpenSections((prev) =>
                  prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]
                )
              }
              onStartEdit={() => setIsDetailEditing(true)}
              onFinishEdit={() => setIsDetailEditing(false)}
              editSubmitTrigger={editSubmitTrigger}
              editCancelTrigger={editCancelTrigger}
            />
          </Modal>
        </div>
      )}

      <Modal
        isOpen={showFormModal}
        onClose={() => setShowFormModal(false)}
        title={editingMeal ? 'Редактирование приёма пищи' : 'Новый приём пищи'}
      >
        <MealForm
          meal={editingMeal}
          onSubmit={handleFormSubmit}
          onCancel={() => setShowFormModal(false)}
          autoGeneratedName={!editingMeal ? autoGeneratedName : undefined}
        />
      </Modal>

      <ConfirmModal
        isOpen={!!mealToDelete}
        onClose={() => setMealToDelete(null)}
        onConfirm={handleConfirmDelete}
        title="Подтверждение"
        variant="danger"
        confirmText="Удалить"
      >
        <p>
          Удалить приём пищи <span className="font-bold">{mealToDelete?.name}</span>?
        </p>
      </ConfirmModal>

      <ConfirmModal
        isOpen={showBulkDeleteConfirm}
        onClose={() => setShowBulkDeleteConfirm(false)}
        onConfirm={handleConfirmBulkDelete}
        title="Подтверждение"
        variant="danger"
        confirmText="Удалить"
      >
        <p>
          Вы уверены, что хотите удалить {selectedMealIds.length} приёмов пищи?
          <br />
          <span className="text-sm text-muted-foreground mt-2 block">
            Это действие нельзя отменить. Все данные о приёмах пищи будут потеряны.
          </span>
        </p>
      </ConfirmModal>
    </div>
  );
};

export default MealsPage;
