// src/pages/MealsPage.tsx

import React, { useState, useMemo, useCallback, useEffect } from 'react';
import {
  Utensils,
  Trash2,
  Copy,
  Upload,
  X,
  CheckSquare,
  CheckCheck,
  LayoutList,
  Grid3X3,
  Filter,
  Download,
  Flame,
  Weight,
  Hash,
  Beef,
  Droplet,
  Wheat,
  Tag,
} from 'lucide-react';
import { useMealStore } from '../stores/useMealStore';
import useProductStore from '../stores/useProductStore';
import useDishStore from '../stores/useDishStore';
import useMealTypesStore from '../stores/useMealTypesStore';
import { useSettingsStore } from '../stores/useSettingsStore';
import { useIsMobile } from '../hooks/useIsMobile';
import { useViewMode } from '../hooks/useViewMode';
import type { Meal, MealData, ImportedJsonData } from '../types';
import Button from '../ui/Button';
import EntityCard from '../ui/EntityCard';
import EntityListItem, { MetaItem } from '../ui/EntityListItem';
import { mealEntityConfig } from '../config/mealEntityConfig';
import { calculateNutrition } from '../components/meals/mealFormUtils';
import Modal from '../ui/Modal';
import ConfirmModal from '../ui/ConfirmModal';
import MealForm from '../components/meals/MealForm';
import MealDetail from '../components/meals/MealDetail';
import CreateMealButton from '../components/meals/CreateMealButton';
import { generateUniqueMealName } from '../components/meals/mealFormUtils';
import { exportBulkMealsToJson } from '../utils/backup';
import ImportMealsModal from '../components/meals/ImportMealsModal';
import { useSearchParams } from 'react-router-dom';

const MealsPage: React.FC = () => {
  const { meals, addMeal, updateMeal, removeMeal } = useMealStore();
  const { products } = useProductStore();
  const { dishes } = useDishStore();
  const { mealTypes } = useMealTypesStore();
  const isMobile = useIsMobile();
  const { viewMode, toggleViewMode } = useViewMode('meals');
  const getVisibleFields = useSettingsStore((state) => state.getVisibleFields);
  const [activeId, setActiveId] = useState<number | null>(null);
  const [detailEditTrigger, setDetailEditTrigger] = useState(0);
  const [showFormModal, setShowFormModal] = useState(false);
  const [editingMeal, setEditingMeal] = useState<Meal | null>(null);
  const [creatingMeal, setCreatingMeal] = useState(false);
  const [isDetailEditing, setIsDetailEditing] = useState(false);
  const [mealToDelete, setMealToDelete] = useState<Meal | null>(null);
  const [openSections, setOpenSections] = useState<string[]>(['basic-info', 'composition']);
  const [showBulkDeleteConfirm, setShowBulkDeleteConfirm] = useState(false);
  const [showImportModal, setShowImportModal] = useState(false);
  const [importFileContent, setImportFileContent] = useState<ImportedJsonData | null>(null);
  const [searchParams, setSearchParams] = useSearchParams();

  const [selectedMealIds, setSelectedMealIds] = useState<number[]>([]);
  const [showMultiSelect, setShowMultiSelect] = useState(false);
  const [autoGeneratedName, setAutoGeneratedName] = useState<string>('');
  const [editSubmitTrigger, _setEditSubmitTrigger] = useState(0);
  const [editCancelTrigger, _setEditCancelTrigger] = useState(0);
  const visibleFields = getVisibleFields('meals');

  // URL synchronization - handle selectedId and mealId query parameters
  useEffect(() => {
    const selectedId = searchParams.get('selectedId');
    const mealId = searchParams.get('mealId');

    // Handle mealId parameter (from meal type usage block)
    if (mealId && meals.some((m) => m.id === Number(mealId))) {
      setActiveId(Number(mealId));
      // Remove the query parameter from the URL
      setSearchParams({}, { replace: true });
      // Scroll to the detail pane
      setTimeout(() => {
        const detailPane = document.getElementById('meal-detail-pane');
        if (detailPane) {
          detailPane.scrollIntoView({ behavior: 'smooth' });
        }
      }, 100);
      return;
    }

    // Handle selectedId parameter (existing logic)
    if (selectedId && meals.some((m) => m.id === Number(selectedId))) {
      setActiveId(Number(selectedId));
      // Remove the query parameter from the URL
      setSearchParams({}, { replace: true });
      // Scroll to the detail pane
      setTimeout(() => {
        const detailPane = document.getElementById('meal-detail-pane');
        if (detailPane) {
          detailPane.scrollIntoView({ behavior: 'smooth' });
        }
      }, 100);
    }
  }, [searchParams, meals, setSearchParams]);

  const selectedMeal = useMemo(
    () => meals.find((m) => m.id === activeId) || null,
    [activeId, meals]
  );

  const handleEdit = useCallback((meal: Meal) => {
    setActiveId(meal.id);
    setIsDetailEditing(true);
    // Не меняем состояние openSections - только пользователь управляет сворачиванием
    setDetailEditTrigger((t) => t + 1);
  }, []);

  const generateMealName = useCallback(() => {
    return generateUniqueMealName(meals);
  }, [meals]);

  useEffect(() => {
    if (creatingMeal || showFormModal) {
      setAutoGeneratedName(generateMealName());
    }
  }, [creatingMeal, showFormModal, generateMealName]);

  const handleInlineCreate = useCallback(
    (formData: MealData) => {
      const dataWithName = {
        ...formData,
        name: formData.name.trim() || generateMealName(),
      };
      const created = addMeal(dataWithName);
      setActiveId(created.id);
      setCreatingMeal(false);
    },
    [addMeal, generateMealName]
  );

  const handleFormSubmit = useCallback(
    (formData: MealData) => {
      if (editingMeal) {
        updateMeal(editingMeal.id, formData);
      } else {
        const dataWithName = {
          ...formData,
          name: formData.name.trim() || generateMealName(),
        };
        const created = addMeal(dataWithName);
        setActiveId(created.id);
      }
      setShowFormModal(false);
      setEditingMeal(null);
    },
    [editingMeal, addMeal, updateMeal, generateMealName]
  );

  const handleRequestDelete = useCallback((meal: Meal) => setMealToDelete(meal), []);
  const handleConfirmDelete = useCallback(() => {
    if (!mealToDelete) return;
    if (mealToDelete.id === activeId) setActiveId(null);
    removeMeal(mealToDelete.id);
    setMealToDelete(null);
  }, [mealToDelete, activeId, removeMeal]);

  const toggleMultiSelect = () => {
    setShowMultiSelect((s) => !s);
    if (showMultiSelect) setSelectedMealIds([]);
  };

  const toggleMealSelection = (mealId: number) => {
    setSelectedMealIds((prev: number[]) =>
      prev.includes(mealId) ? prev.filter((id) => id !== mealId) : [...prev, mealId]
    );
  };

  const selectAllMeals = () => setSelectedMealIds(meals.map((meal: Meal) => meal.id));
  const exitMultiSelectMode = () => {
    setShowMultiSelect(false);
    setSelectedMealIds([]);
  };

  const handleBulkDelete = () => {
    if (selectedMealIds.length === 0) return;
    setShowBulkDeleteConfirm(true);
  };

  const handleConfirmBulkDelete = () => {
    selectedMealIds.forEach((id) => {
      if (id === activeId) setActiveId(null);
      removeMeal(id);
    });
    exitMultiSelectMode();
    setShowBulkDeleteConfirm(false);
  };

  const handleBulkClone = () => {
    if (selectedMealIds.length === 0) return;
    console.log(`Cloning meals: ${selectedMealIds.join(', ')}`);
  };

  const handleBulkExport = () => {
    if (selectedMealIds.length === 0) return;
    const selectedMeals = meals.filter((meal) => selectedMealIds.includes(meal.id));
    exportBulkMealsToJson(selectedMeals);
  };

  const handleImportClick = () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.json';
    input.onchange = (e) => {
      const file = (e.target as HTMLInputElement).files?.[0];
      if (file) {
        const reader = new FileReader();
        reader.onload = (event) => {
          try {
            const jsonContent = event.target?.result as string;
            const data = JSON.parse(jsonContent);
            setImportFileContent(data);
            setShowImportModal(true);
          } catch (error) {
            console.error('Error parsing JSON file:', error);
            // Show error toast
          }
        };
        reader.readAsText(file);
      }
    };
    input.click();
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="mb-6 sm:mb-8 px-4 sm:px-2">
        <div className="flex items-center justify-between gap-4">
          <h1 className="text-2xl sm:text-3xl font-semibold text-foreground tracking-tight">
            Приёмы пищи
          </h1>
          <div className="flex items-center gap-2 min-w-[320px] justify-end">
            {!showMultiSelect ? (
              <>
                <Button
                  onClick={() => console.log('Filters would be implemented here')}
                  variant="secondary"
                  size="icon"
                  title="Фильтры"
                  aria-label="Показать фильтры"
                >
                  <Filter className="w-4 h-4" />
                </Button>

                <Button
                  variant="secondary"
                  size="icon"
                  title="Импорт"
                  aria-label="Импорт"
                  onClick={handleImportClick}
                >
                  <Download className="w-4 h-4" />
                </Button>

                <Button
                  onClick={toggleViewMode}
                  variant="secondary"
                  size="icon"
                  title={viewMode === 'default' ? 'Компактный вид' : 'Полный вид'}
                  aria-label={viewMode === 'default' ? 'Компактный вид' : 'Полный вид'}
                >
                  {viewMode === 'default' ? (
                    <LayoutList className="w-4 h-4" />
                  ) : (
                    <Grid3X3 className="w-4 h-4" />
                  )}
                </Button>

                <Button
                  onClick={toggleMultiSelect}
                  variant="secondary"
                  size="icon"
                  title="Выделить"
                  aria-label="Выделить"
                >
                  <CheckSquare className="w-4 h-4" />
                </Button>

                <CreateMealButton
                  onClick={() => {
                    if (isDetailEditing) return;
                    setCreatingMeal(true);
                    setActiveId(null);
                    setOpenSections(['basic-info', 'composition']);
                  }}
                  disabled={isDetailEditing || creatingMeal}
                  showText={false}
                />
              </>
            ) : (
              <div className="flex items-center gap-2 h-9 min-w-[320px] justify-end">
                <div className="bg-primary/10 text-primary px-3 py-2 rounded-lg text-sm font-medium flex items-center">
                  <span>{`${selectedMealIds.length} из ${meals.length} выделено`}</span>
                </div>

                <Button
                  variant="secondary"
                  size="icon"
                  onClick={selectAllMeals}
                  disabled={selectedMealIds.length === meals.length}
                  title="Выделить все"
                >
                  <CheckCheck className="w-4 h-4" />
                </Button>

                <div className="flex items-center gap-1">
                  <Button
                    variant="secondary"
                    size="icon"
                    onClick={handleBulkClone}
                    disabled={selectedMealIds.length === 0}
                    title="Клонировать"
                  >
                    <Copy className="w-4 h-4" />
                  </Button>
                  <Button
                    variant="secondary"
                    size="icon"
                    onClick={handleBulkExport}
                    disabled={selectedMealIds.length === 0}
                    title="Экспорт"
                  >
                    <Upload className="w-4 h-4" />
                  </Button>
                  <Button
                    variant="danger"
                    size="icon"
                    onClick={handleBulkDelete}
                    disabled={selectedMealIds.length === 0}
                    title="Удалить"
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>

                <Button onClick={exitMultiSelectMode} variant="ghost" size="icon" title="Закрыть">
                  <X className="w-4 h-4" />
                </Button>
              </div>
            )}
          </div>
        </div>
      </div>

      {meals.length > 0 || creatingMeal ? (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 lg:gap-6">
          <div className="lg:col-span-1 space-y-3 overflow-y-auto pr-2 custom-scrollbar max-h-[calc(100vh-12rem)] pl-1 pb-4 pt-2">
            {meals.map((meal) => {
              // Compute totals for nutrition and weight
              let totalCalories = 0,
                totalProteins = 0,
                totalFats = 0,
                totalCarbs = 0,
                totalWeight = 0;

              meal.items.forEach((item) => {
                const n = calculateNutrition(item, products, dishes);
                if (n) {
                  totalCalories += n.calories;
                  totalProteins += n.proteins;
                  totalFats += n.fats;
                  totalCarbs += n.carbs;
                }
                if (item.type === 'product') {
                  totalWeight += 'weight' in item ? item.weight || 0 : 0;
                } else if (item.type === 'dish') {
                  const dish = dishes.find((d) => d.id === item.itemId);
                  if (dish) {
                    totalWeight += dish.products.reduce((sum, p) => sum + p.weight, 0);
                  }
                }
              });
              const actions = mealEntityConfig
                .getActions({
                  onEdit: () => handleEdit(meal),
                  onDelete: () => handleRequestDelete(meal),
                })
                .map((action) => ({
                  ...action,
                  disabled: isDetailEditing && meal.id !== activeId,
                  onClick: (e: React.MouseEvent) => {
                    e.preventDefault();
                    e.stopPropagation();
                    if (isDetailEditing && meal.id !== activeId) return;
                    if (action.label === 'Редактировать') {
                      handleEdit(meal);
                    } else if (action.label === 'Удалить') {
                      handleRequestDelete(meal);
                    }
                  },
                }));

              const isCardDisabled = isDetailEditing && activeId !== null && meal.id !== activeId;

              const metaMap: Record<string, MetaItem | null> = {
                items:
                  meal.items.length > 0
                    ? {
                        icon: Hash,
                        text: meal.items.length,
                        tooltip: 'Количество компонентов',
                      }
                    : null,
                mealType: meal.mealTypeId
                  ? {
                      icon: Tag,
                      text: mealTypes.find((mt) => mt.id === meal.mealTypeId)?.name || 'Тип',
                      tooltip: 'Тип приёма пищи',
                    }
                  : null,
                calories: {
                  icon: Flame,
                  text: Math.round(totalCalories),
                  className: 'text-orange-600',
                  tooltip: 'Калории',
                },
                proteins: {
                  icon: Beef,
                  text: Math.round(totalProteins * 10) / 10,
                  className: 'text-blue-600',
                  tooltip: 'Белки',
                },
                fats: {
                  icon: Droplet,
                  text: Math.round(totalFats * 10) / 10,
                  className: 'text-yellow-600',
                  tooltip: 'Жиры',
                },
                carbs: {
                  icon: Wheat,
                  text: Math.round(totalCarbs * 10) / 10,
                  className: 'text-green-600',
                  tooltip: 'Углеводы',
                },
                weight: {
                  icon: Weight,
                  text: Math.round(totalWeight),
                  tooltip: 'Общий вес',
                },
              };

              const metaItems = visibleFields
                .map((id) => metaMap[id])
                .filter((item): item is MetaItem => item !== null);

              return viewMode === 'compact' ? (
                <EntityListItem
                  key={meal.id}
                  title={mealEntityConfig.views.card.title(meal)}
                  meta={metaItems}
                  isSelected={activeId === meal.id}
                  isMultiSelected={selectedMealIds.includes(meal.id)}
                  onSelect={
                    isCardDisabled
                      ? undefined
                      : () => {
                          // Toggle selection - if already selected, deselect it
                          setActiveId(activeId === meal.id ? null : meal.id);
                        }
                  }
                  onMultiSelect={isCardDisabled ? undefined : () => toggleMealSelection(meal.id)}
                  onRequestMultiSelectMode={() => {
                    if (!showMultiSelect) {
                      setShowMultiSelect(true);
                      setSelectedMealIds([meal.id]);
                    }
                  }}
                  menuItems={actions}
                  showMultiSelect={showMultiSelect}
                  variant="meal"
                />
              ) : (
                <EntityCard
                  key={meal.id}
                  title={mealEntityConfig.views.card.title(meal)}
                  subtitle={mealEntityConfig.views.card.subtitle?.(meal, {
                    mealType: mealTypes.find((mt) => mt.id === meal.mealTypeId),
                  })}
                  icon={mealEntityConfig.getIcon(meal)}
                  isSelected={activeId === meal.id}
                  isMultiSelected={selectedMealIds.includes(meal.id)}
                  onSelect={
                    isCardDisabled
                      ? undefined
                      : () => {
                          // Toggle selection - if already selected, deselect it
                          setActiveId(activeId === meal.id ? null : meal.id);
                        }
                  }
                  onMultiSelect={isCardDisabled ? undefined : () => toggleMealSelection(meal.id)}
                  onRequestMultiSelectMode={() => {
                    if (!showMultiSelect) {
                      setShowMultiSelect(true);
                      setSelectedMealIds([meal.id]);
                    }
                  }}
                  menuItems={actions}
                  showMultiSelect={showMultiSelect}
                  variant="meal"
                  nutrition={{
                    calories: Math.round(totalCalories),
                    proteins: Math.round(totalProteins * 10) / 10,
                    fats: Math.round(totalFats * 10) / 10,
                    carbs: Math.round(totalCarbs * 10) / 10,
                    weight: Math.round(totalWeight),
                    itemsCount: meal.items.length,
                  }}
                />
              );
            })}
          </div>

          <div
            className="lg:col-span-2 hidden lg:block max-h-[calc(100vh-12rem)] overflow-y-auto pr-2 custom-scrollbar pt-2"
            id="meal-detail-pane"
          >
            {creatingMeal ? (
              <div className="pl-1">
                <MealForm
                  meal={null}
                  onSubmit={handleInlineCreate}
                  onCancel={() => setCreatingMeal(false)}
                  autoGeneratedName={autoGeneratedName}
                  focusName
                />
              </div>
            ) : selectedMeal ? (
              <MealDetail
                meal={selectedMeal}
                onEdit={() => setIsDetailEditing(true)}
                editTrigger={detailEditTrigger}
                openSections={openSections}
                onToggleSection={(id) =>
                  setOpenSections((prev) =>
                    prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]
                  )
                }
                onStartEdit={() => setIsDetailEditing(true)}
                onFinishEdit={() => setIsDetailEditing(false)}
                editSubmitTrigger={editSubmitTrigger}
                editCancelTrigger={editCancelTrigger}
              />
            ) : (
              <div className="h-full flex items-start justify-center pt-16">
                <div className="text-center p-4">
                  <div className="w-20 h-20 bg-muted rounded-2xl flex items-center justify-center mx-auto mb-4">
                    <Utensils className="w-10 h-10 text-muted-foreground" />
                  </div>
                  <h3 className="text-lg font-medium text-foreground mb-2">Выберите приём пищи</h3>
                  <p className="text-muted-foreground">
                    Кликните на карточку для просмотра подробной информации.
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      ) : (
        <div className="h-full flex flex-col items-center justify-center py-16">
          <Utensils className="w-12 h-12 mx-auto mb-4 opacity-50" />
          <h3 className="text-lg font-medium text-foreground">Приёмов пищи пока нет</h3>
          <p className="text-sm text-muted-foreground mt-2">
            Создайте первый шаблон, чтобы быстро добавлять его в раскладки.
          </p>
          <div className="mt-4 inline-block">
            <CreateMealButton
              onClick={() => {
                setCreatingMeal(true);
                setActiveId(null);
                setOpenSections(['basic-info', 'composition']);
              }}
              variant="primary"
              showText={true}
            />
          </div>
        </div>
      )}

      {isMobile && activeId !== null && (
        <div className="lg:hidden">
          <Modal
            isOpen={activeId !== null}
            onClose={() => setActiveId(null)}
            title={selectedMeal?.name || 'Детали'}
          >
            <MealDetail
              meal={selectedMeal}
              onEdit={() => {
                if (selectedMeal) {
                  handleEdit(selectedMeal);
                  setActiveId(null);
                }
              }}
              openSections={openSections}
              onToggleSection={(id) =>
                setOpenSections((prev) =>
                  prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]
                )
              }
              onStartEdit={() => setIsDetailEditing(true)}
              onFinishEdit={() => setIsDetailEditing(false)}
              editSubmitTrigger={editSubmitTrigger}
              editCancelTrigger={editCancelTrigger}
            />
          </Modal>
        </div>
      )}

      <Modal
        isOpen={showFormModal}
        onClose={() => setShowFormModal(false)}
        title={editingMeal ? 'Редактирование приёма пищи' : 'Новый приём пищи'}
      >
        <MealForm
          meal={editingMeal}
          onSubmit={handleFormSubmit}
          onCancel={() => setShowFormModal(false)}
          autoGeneratedName={!editingMeal ? autoGeneratedName : undefined}
          openSections={openSections}
          onToggleSection={(id) =>
            setOpenSections((prev) =>
              prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]
            )
          }
        />
      </Modal>

      <ConfirmModal
        isOpen={!!mealToDelete}
        onClose={() => setMealToDelete(null)}
        onConfirm={handleConfirmDelete}
        title="Подтверждение"
        variant="danger"
        confirmText="Удалить"
      >
        <p>
          Удалить приём пищи <span className="font-bold">{mealToDelete?.name}</span>?
        </p>
      </ConfirmModal>

      <ConfirmModal
        isOpen={showBulkDeleteConfirm}
        onClose={() => setShowBulkDeleteConfirm(false)}
        onConfirm={handleConfirmBulkDelete}
        title="Подтверждение"
        variant="danger"
        confirmText="Удалить"
      >
        <p>
          Вы уверены, что хотите удалить {selectedMealIds.length} приёмов пищи?
          <br />
          <span className="text-sm text-muted-foreground mt-2 block">
            Это действие нельзя отменить. Все данные о приёмах пищи будут потеряны.
          </span>
        </p>
      </ConfirmModal>

      <ImportMealsModal
        isOpen={showImportModal}
        onClose={() => {
          setShowImportModal(false);
          setImportFileContent(null);
        }}
        fileContent={importFileContent}
      />
    </div>
  );
};

export default MealsPage;
